########################### Navigation ###################################
menu:
  # main menu
  main:
    - { name: Home, url: "/" }
    - { name: Contact, url: "contact.html" }

  ##### Dropdown menu ######

  # - name: dropdown
  #   submenu:
  #   - name : "d1"
  #     url : "#"
  #   - name : "d2"
  #     url : "#"

  ##########################

  # Footer menu
  footer:
    - { name: Home, url: "/" }
    - { name: Contact, url: "contact.html" }

######################### Default Parameters ###########################

# logo
logo: "/assets/images/logosmall.png"
# meta data
author: "Diogo Winck"
description: "This is meta description"
# google analitycs ID
google_analitycs_id: "" # your id
# contact form action
contact_form_action: https://formspree.io/f/mpzezbaa
# copyright
copyright: "Copyright &copy; 2023 Designed and Developed by [Themefisher](https://themefisher.com)"

# preloader
preloader:
  enable: true
  preloader: "" # use png, jpg, svg or gif format

# search
search:
  enable: true

############################## Social Site ##########################
## social:
##  
##  - name: "twitter"
##    icon: "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
##    link: "https://twitter.com/DiogoWinck"
##
##  - name: "github"
##    icon: "ti-github" # themify icon pack https://themify.me/themify-icons
##    link: "https://github.com/dvwinck"
##
##  - name: "linkedin"
##    icon: "ti-linkedin" # themify icon pack https://themify.me/themify-icons
##    link: "https://www.linkedin.com/in/diogowinck/"
